### ISSUE TITLE
网易的登陆API密码需MD5加密 + 这个项目没有Licence

### ISSUE THREAD

**Issue by LER0ever** [fengleyl/NetEaseMusic#2]
当前登陆代码无法登陆
**网易现在的登陆API密码需要MD5加密的，具体是34行和51行从**
```'password': password,```
**改成**
```'password': hashlib.md5(str(password)).hexdigest(),```
就可以登陆了。(我就不PR了)

还有就是请问这个项目是什么协议开源的？我最近刚好在做类似的项目: [LER0ever/Israfil](https://github.com/LER0ever/Israfil)，可能需要用到这个项目的一部分代码，**所以想问下大神这个项目像[这样声明Copyright](https://github.com/LER0ever/Israfil#copyright)可以使用吗？**

**Comment by fengleyl** [comment]
完全可以使用，这个项目使用MIT Licence。
当时忘记说明了。。。

**Comment by LER0ever** [comment]
好的谢谢！
